import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { allContracts } from '@platform/contracts';
import { loadManifests } from './lib/manifests';
import { read, ROOT, type CheckResult } from './lib/workspace';

const MAP = join(ROOT, 'docs/module-map.md');

export async function renderModuleMap(): Promise<string> {
  const lines = [
    '# Module map',
    '',
    'Generated by `pnpm module-map`. Do not edit by hand.',
    '',
    '## Modules',
    '',
  ];
  const manifests = (await loadManifests()).flatMap((m) => (m.manifest ? [m.manifest] : []));
  if (manifests.length === 0) lines.push('_No modules yet._', '');
  for (const m of manifests.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`### ${m.name} (${m.version})`, '', m.description, '');
    const list = (label: string, items: string[]) =>
      lines.push(`- **${label}:** ${items.length ? items.join(', ') : 'none'}`);
    list(
      'Provides',
      m.provides.map((p) => `${p.capability}@v${p.version}`),
    );
    list(
      'Requires',
      m.requires.map(
        (r) =>
          `${r.capability}@v${r.version}${r.optional ? ' (optional)' : ` (fallback: ${r.fallback})`}`,
      ),
    );
    list(
      'Publishes',
      m.publishes.map((p) => `${p.event}@v${p.version}`),
    );
    list(
      'Subscribes',
      m.subscribes.map((p) => `${p.event}@v${p.version}`),
    );
    list('Extension points', m.extensionPoints);
    lines.push(`- **Public API:** packages/modules/${m.name}/src/public-api.ts`, '');
  }
  lines.push('## Contracts', '');
  if (allContracts.length === 0) lines.push('_No contracts yet._', '');
  for (const c of [...allContracts].sort((a, b) => a.name.localeCompare(b.name)))
    lines.push(`- \`${c.kind}\` **${c.name}@v${c.version}**: ${c.description}`);
  return `${lines.join('\n').trimEnd()}\n`;
}

export async function checkModuleMap(): Promise<CheckResult> {
  let current = '';
  try {
    current = read(MAP);
  } catch {
    /* missing file is reported below */
  }
  const fresh = await renderModuleMap();
  return {
    check: 'module-map',
    problems: current === fresh ? [] : ['docs/module-map.md is out of date: run pnpm module-map'],
  };
}

if (process.argv[1]?.endsWith('module-map.ts') && process.argv[2] === 'write') {
  writeFileSync(MAP, await renderModuleMap());
  console.info('docs/module-map.md written');
}
